export const ACTIONS = {
    TOGGLE_LOADER: "TOGGLE_LOADER",
    SET_PROGRESS: "SET_PROGRESS",
    SET_LOCKED: "SET_LOCKED",
    SET_NAME: "SET_NAME",
    SET_SCHEDULE_DATA: "SET_SCHEDULE_DATA",
    SET_STEPS_TEXT_DATA: "SET_STEPS_TEXT_DATA",
    SET_MENU_DATA: "SET_MENU_DATA",
    SET_DARK_THEME_DATA: "SET_DARK_THEME_DATA",
    SET_LIGHT_THEME_DATA: "SET_LIGHT_THEME_DATA",
    SET_CURRENT_SECTION: "SET_CURRENT_SECTION",
}